<?xml version="1.0" encoding="UTF-8"?>
<!--
 |  Copyright 2015 Adobe Systems Incorporated
 |
 |  Licensed under the Apache License, Version 2.0 (the "License");
 |  you may not use this file except in compliance with the License.
 |  You may obtain a copy of the License at
 |
 |      http://www.apache.org/licenses/LICENSE-2.0
 |
 |  Unless required by applicable law or agreed to in writing, software
 |  distributed under the License is distributed on an "AS IS" BASIS,
 |  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 |  See the License for the specific language governing permissions and
 |  limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- ====================================================================== -->
    <!-- P A R E N T  P R O J E C T  D E S C R I P T I O N                      -->
    <!-- ====================================================================== -->
    <parent>
        <groupId>com.community.aemlab</groupId>
        <artifactId>oneweb</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <!-- ====================================================================== -->
    <!-- P R O J E C T  D E S C R I P T I O N                                   -->
    <!-- ====================================================================== -->
    <artifactId>oneweb.ui.content</artifactId>
    <packaging>content-package</packaging>
    <name>AEMLab OneWeb - UI content</name>
    <description>UI content package for AEMLab OneWeb</description>
    
    <!-- ====================================================================== -->
    <!-- P R O J E C T  P R O P E R T I E S                                     -->
    <!-- ====================================================================== -->
 
    <properties>
    	<env.ENV_TYPE>dev</env.ENV_TYPE>
    	<env.GROOVY_LOG_LEVEL>2</env.GROOVY_LOG_LEVEL>
    	<replacement.script.path>${project.basedir}/src/main/resources/script</replacement.script.path>
    	<replacement.script.name>replace-cac-placeholder.groovy</replacement.script.name>
    	<replacement.script.config>aemlab_config.json</replacement.script.config>
    </properties>
    

    <!-- ====================================================================== -->
    <!-- B U I L D   D E F I N I T I O N                                        -->
    <!-- ====================================================================== -->
    <build>
        <plugins>
			<!-- ====================================================================== -->
            <!-- G R O O V Y   P L U G I N S                                            -->
            <!-- ====================================================================== -->
            <plugin>
				<groupId>org.codehaus.gmaven</groupId>
				<artifactId>groovy-maven-plugin</artifactId>
				<version>2.1.1</version>
				<executions>
					<execution>
						<id>cac-placeholder-replace</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>execute</goal>
						</goals>
						<configuration>
							<properties>
								<env>${env.ENV_TYPE}</env>
								<configData>${replacement.script.path}/${replacement.script.config}</configData>
								<logLevel>${env.GROOVY_LOG_LEVEL}</logLevel>
								<baseDir>${project.basedir}</baseDir>
							</properties>
                            <source>${replacement.script.path}/${replacement.script.name}</source>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
					<dependency>
						<groupId>org.apache.groovy</groupId>
                        <artifactId>groovy-all</artifactId>
                        <version>4.0.22</version>
                        <type>pom</type>
                    </dependency>
                </dependencies>
            </plugin>
            
            <!-- Copy files from the 'src' directory to the 'target' directory for replacement.-->
            <plugin>
	            <groupId>org.apache.maven.plugins</groupId>
	            <artifactId>maven-resources-plugin</artifactId>
	            <executions>
	                <execution>
	                    <id>copy-jcrroot-to-target</id>
	                    <phase>process-resources</phase>
	                    <goals>
	                        <goal>copy-resources</goal>
	                    </goals>
	                    <configuration>
	                        <outputDirectory>${project.build.directory}/classes</outputDirectory>
	                        <resources>
	                            <resource>
	                                <directory>src/main/content/jcr_root</directory>
	                                <includes>
	                                    <include>**/*</include> <!-- Copy all files -->
	                                </includes>
	                            </resource>
	                        </resources>
	                    </configuration>
	                </execution>
	            </executions>
	        </plugin>

            <!-- ====================================================================== -->
            <!-- V A U L T   P A C K A G E   P L U G I N S                              -->
            <!-- ====================================================================== -->
            <plugin>
                <groupId>org.apache.jackrabbit</groupId>
                <artifactId>filevault-package-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <group>com.community.aemlab</group>
                    <name>oneweb.ui.content</name>
                    <packageType>content</packageType>
                    <jcrRootSourceDirectory>${project.build.outputDirectory}</jcrRootSourceDirectory>
                    <excludes>*groovy</excludes>
                    <accessControlHandling>merge</accessControlHandling>
                    <properties>
                        <cloudManagerTarget>none</cloudManagerTarget>
                    </properties>
                    <dependencies>
                        <dependency>
                            <groupId>com.community.aemlab</groupId>
                            <artifactId>oneweb.ui.apps</artifactId>
                            <version>${project.version}</version>
                        </dependency>
                    </dependencies>
                    <group>AEMLab</group>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <!-- ====================================================================== -->
    <!-- D E P E N D E N C I E S                                                -->
    <!-- ====================================================================== -->
    <dependencies>
        <dependency>
            <groupId>com.community.aemlab</groupId>
            <artifactId>oneweb.core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.community.aemlab</groupId>
            <artifactId>oneweb.ui.apps</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.adobe.aem</groupId>
            <artifactId>aem-sdk-api</artifactId>
        </dependency>
    </dependencies>
</project>
